### ISSUE TITLE
Match as many terms as possible (tags intersection)

### ISSUE THREAD

**Issue by kilianc** [RedisLabsModules/RediSearch#191]
I have been scratching my head around possible implementations with `~` and `|` but none of them work as I want (at least I think).

This is an example use case:

I am indexing an image by features (output of a classifier) and I am storing these features in a `features` field in the index. The search input is another image running through the same classifier outputting another array of features.

Indexed Image:

```js
features: ['red', 'sad', 'van gogh', 'sun', 'painting', 'antique', '1800', 'expensive', 'drawing']
```

Search Input Image

```js
features: ['red', 'happy', 'painting', '1900', 'cheap', 'drawing', 'cars', 'Italy']
```

Is there a way to search and score by the longest intersection fo those two arrays?

N.B. I am still using the `$tag1$ $tag2$` trick to search in lists

**Comment by dvirsky** [comment]
No, actually that was sorted like that due to document order. I'll fix that as well. It should yield correct results. 
I'll fix both tomorrow.

**Comment by kilianc** [comment]
@dvirsky I just found the same bug. Shards went crazy. I was collecting more data before opening an issue.

In my case it was a query like this:

```
ft.search idxname
  (@tags:$tag$)
  (@othertags:$tag2$ $tag3$)
  ((@text:sup)|(@alttext:sup)|(@features:~$f1$ ~$f2$ ~$f3$ ~$f4$ ~$f5$))
  LIMIT 0 20
```

**Comment by kilianc** [comment]
I just added `$$` to all tags fields at indexing time so that I can keep $$ as mandatory at search time. 👍

**Comment by dvirsky** [comment]
@kilianc Just pushed  a fix for the infinite loop to master. I'll work on the scoring tomorrow, I have a flight to catch in a few hours :)

**Comment by dvirsky** [comment]
ok, I fixed the other issue as well. I see there's a slight problem there still, but it works.

```
127.0.0.1:6379> ft.search idx "~foo ~bar ~baz ~gaz" scorer DISMAX withscores
 1) (integer) 4
 2) "4"
 3) "4"
 4) 1) "tags"
    2) "foo bar baz gaz"
 5) "3"
 6) "2"
 7) 1) "tags"
    2) "foo bar baz"
 8) "2"
 9) "2"
10) 1) "tags"
    2) "foo bar"
11) "1"
12) "1"
13) 1) "tags"
    2) "foo"
```

**Comment by dvirsky** [comment]
I'll release a new version of the enterprise module tomorrow or Monday. Thanks for reporting this!

**Comment by kilianc** [comment]
Just so you know, even with `field: $$ ~$asda$` still crashes.

Looking forward to new docker image and enterprise release!

**Comment by dvirsky** [comment]
I don't the dollar thingie has any effect. You can look at ft.explain if
you want to be sure.

**Comment by kilianc** [comment]
@dvirsky is it expected behavior that the index becomes corrupted after this bug happens and I restart the nodes?

**Comment by dvirsky** [comment]
No, it should not affect the index at all.

**Comment by kilianc** [comment]
After I execute the offending query search becomes unresponsive and shards are marked as unresponsive + replication in progress on dashboard. After a node reboot I get the error index not found but memory usage and keys are there.

**Comment by dvirsky** [comment]
What version of the enterprise search are you running?
Let me release a new version with this issue resolved and try it again.

**Comment by dvirsky** [comment]
@kilianc I've released a new version of the enterprise search that fixes the optional infinite loop. Do you have the mechanism to upgrade the enterprise module?

I'm still travelling but I'll have tomorrow free and I can help you.

**Comment by dvirsky** [comment]
@kilianc any chance you can invite me to the slack channel you've set up? dvir at redis labs

**Comment by kilianc** [comment]
@dvirsky done

**Comment by kilianc** [comment]
> What version of the enterprise search are you running?
Redis Enterprise 5.0.0-16

> Do you have the mechanism to upgrade the enterprise module?
Guy sent me instructions but I can't figure it out
