### ISSUE TITLE
"Module path/to/module/module.so initialization failed. Module not loaded" when cluster mode enabled

### ISSUE THREAD

**Issue by badnessJust** [RedisLabsModules/RediSearch#25]
When cluster mode is enabled in the config file like so: 
`port 6379`
`cluster-enabled yes`
`cluster-config-file nodes.conf`
`cluster-node-timeout 5000`
`appendonly yes`
`loadmodule /path/RediSearch/src/module.so`
I get the error "Module path/to/module/module.so initialization failed. Module not loaded".
The module however loads fine in standalone mode
Am I doing something wrong? Is there a special configuration for cluster mode?

**Comment by dvirsky** [comment]
Hi. I've never tried the module in cluster mode, I can check. Cluster support is in the near future roadmap but not supported yet.

It should be possible to  use the module in cluster mode, given that: 1. you name the index with curly braces, i.e. `IDX.CREATE idx{foo} ....`. Since it generates keys that have the prefix of the index name, the index name must be or contain a sharding key.  

and 2. All document ids need to contain curly braces that match the index's curly braces, otherwise you will get sharding violations.

**Comment by dvirsky** [comment]
Ok, after a bit of research, it turns out that denying cluster mode on even one command in a module, prevents it from being loaded in cluster mode. I'm not sure if that's the desired behavior, and I've asked antirez about it. 

In the mean time I'm keeping this issue open as a reminder to disable the cluster "protection" and test the module in cluster situations.

**Comment by dvirsky** [comment]
BTW Seems like this is a bug in Redis itself, although in this case the module indeed should not be used in a cluster.

**Comment by dvirsky** [comment]
Fixed in a previous version.

**Comment by ashutoshtripathi** [comment]
Hi @dvirsky Can I use redisearch module in cluster mode now ? Because I am still facing the issue reported by @badnessJust 
-Thanks
