### ISSUE TITLE
result variations with multiple filters for same field

### ISSUE THREAD

**Issue by manishtoons** [RedisLabsModules/RediSearch#304]
Hi,

I dont know if this behaviour is known, but I found sort of simillar issue https://github.com/RedisLabsModules/RediSearch/issues/284, and try to follow same configuration mentioned there.

So, following statements returnig different result based on their order

```
127.0.0.1:6379> FT.SEARCH Project -@sg_project_code:null @sg_project_code:TECH LIMIT 0 1 NOCONTENT
1) (integer) 86
2) "Project:96"
```

```
EXPLAIN -  NOT{
  @sg_project_code:null
}
```

```
127.0.0.1:6379> FT.SEARCH Project @sg_project_code:TECH -@sg_project_code:null LIMIT 0 1 NOCONTENT
1) (integer) 1
2) "Project:19"

```
```
EXPLAIN - @sg_project_code:UNION {
@sg_project_code:tech
  @sg_project_code:+tech(expanded)
}
```

expected result is to return only one doc as per the documentation. Am i missing anything?

**Comment by dvirsky** [comment]
you need to quote the search terms when doing multiple clauses, otherwise just the first argument gets parsed. 

So you should have written: 

```
> FT.SEARCH "Project @sg_project_code:TECH -@sg_project_code:null" LIMIT 0 1 NOCONTENT

> FT.SEARCH Project "-@sg_project_code:null @sg_project_code:TECH" LIMIT 0 1 NOCONTENT
```

**Comment by manishtoons** [comment]
Thanks for quick response!

I tried putting quotes around search string, but still im getting same result!

```
127.0.0.1:6379> FT.SEARCH Project "@sg_project_code:TECH -@sg_project_code:null" LIMIT 0 1 NOCONTENT
1) (integer) 1
2) "Project:19"

127.0.0.1:6379> FT.SEARCH Project "-@sg_project_code:null @sg_project_code:TECH" LIMIT 0 1 NOCONTENT
1) (integer) 107
2) "Project:76"
```

**Comment by manishtoons** [comment]
ok, I it worked when I added brakets around search terms

```
127.0.0.1:6379> FT.SEARCH Project "(-@sg_project_code:null) (@sg_project_code:tech)" LIMIT 0 10 NOCONTENT
1) (integer) 1
2) "Project:19"

127.0.0.1:6379> FT.SEARCH Project "(@sg_project_code:TECH) -(@sg_project_code:null)" LIMIT 0 10 NOCONTENT
1) (integer) 1
2) "Project:19"

```

**Comment by dvirsky** [comment]
Cool. BTW it's never a good idea to start a query with a negative clause. There is no optimizer that rewrites it, so I'd suggest to use `"(@sg_project_code:TECH) -(@sg_project_code:null)"`

**Comment by manishtoons** [comment]
thanks I'll keep that in mind!

**Comment by manishtoons** [comment]
Hi Dvir,

Thanks for being helpful on the issues which im raising. With the help of redisearch I manage to optimize our existing tools efficiently and easily.

I'm running some test cases to see the differences in speed and performance while doing it im hitting some cases where my result is not matching with my db, but those are really bug in codes and easy to fix, though this one issue which im failing to resolve is following query:

```
127.0.0.1:6379> FT.SEARCH Project "(@sg_project_code:TECH)|(-@sg_project_code:null)" LIMIT 0 100 NOCONTENT
 1) (integer) 86
 2) "Project:19"
 3) "Project:96"
 4) "Project:86"
 5) "Project:75"
 6) "Project:74"
 7) "Project:92"
 8) "Project:73"
 9) "Project:72"
10) "Project:71"
11) "Project:70"
12) "Project:69"
13) "Project:68"
14) "Project:89"
15) "Project:88"
16) "Project:67"
17) "Project:66"
18) "Project:65"
19) "Project:64"
20) "Project:63"
21) "Project:62"
22) "Project:61"
23) "Project:60"
24) "Project:59"
25) "Project:58"
26) "Project:57"
27) "Project:56"
28) "Project:55"
29) "Project:85"
30) "Project:54"
31) "Project:53"
32) "Project:52"
33) "Project:84"
34) "Project:51"
35) "Project:87"
36) "Project:50"
37) "Project:49"
38) "Project:48"
39) "Project:47"
40) "Project:46"
41) "Project:45"
42) "Project:44"
43) "Project:43"
44) "Project:42"
45) "Project:41"
46) "Project:40"
47) "Project:39"
48) "Project:38"
49) "Project:37"
50) "Project:36"
51) "Project:35"
52) "Project:34"
53) "Project:33"
54) "Project:32"
55) "Project:31"
56) "Project:30"
57) "Project:29"
58) "Project:28"
59) "Project:27"
60) "Project:26"
61) "Project:83"
62) "Project:25"
63) "Project:24"
64) "Project:23"
65) "Project:22"
66) "Project:21"
67) "Project:81"
68) "Project:91"
69) "Project:20"
70) "Project:18"
71) "Project:80"
72) "Project:17"
73) "Project:100"
74) "Project:103"
75) "Project:16"
76) "Project:15"
77) "Project:14"
78) "Project:13"
79) "Project:12"
80) "Project:11"
81) "Project:77"
82) "Project:10"
83) "Project:9"
84) "Project:8"
85) "Project:7"
86) "Project:6"
87) "Project:5"

```

which returning 86 documents, where acutally 87 exists! If I run another search with ```INKEYS``` in it you will see the missing key.

```
127.0.0.1:6379> FT.SEARCH Project "(@sg_project_code:TECH)|(-@sg_project_code:null)" INKEYS 1 Project:76 LIMIT 0 1 NOCONTENT                                                                                                                                                      1) (integer) 1                                                                                                                                                                                                                                                                    2) "Project:76"      

```

I put my module in SAFEMODE, TIMEOUT by 2000 and MAXEXPANSIONS 2048 for testing purpose.

```
loadmodule /etc/redis/modules/redisearch.so SAFEMODE MAXEXPANSIONS 2048 TIMEOUT 2000
```

**Comment by dvirsky** [comment]
Can you provide the RDB or a script to recreate the DB so I can reproduce this?

**Comment by manishtoons** [comment]
Hi, attached is rdb file along with commands fired on redis server 

```
FT.SEARCH Project "(@sg_project_code:TECH)|(-@sg_project_code:null)" NOCONTENT LIMIT 0 100 
```

Missing doc - Project:108
```
FT.SEARCH Project "(@sg_project_code:TECH)|(-@sg_project_code:null)" INKEYS 1 Project:108 NOCONTENT LIMIT 0 100 
```

**Comment by dvirsky** [comment]
Hi, I've just pushed a fix to another problem with the negative filter, and it might affect your case as well. Could you please compile the 1.0 or master branch and try again?

**Comment by manishtoons** [comment]
sure, I'll try with latest master and update the result here!

**Comment by manishtoons** [comment]
I re-tried compiling master and still getting same results.
(Though im getting **NI READ!** on stdout along with results?)

```
127.0.0.1:6379>  FT.SEARCH Project "(-@sg_project_code:null)" LIMIT 0 1 NOCONTENT

NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
NI READ!
1) (integer) 86
2) "Project:96"

```

**Comment by dvirsky** [comment]
Oops, that shouldn't have been committed, but it's harmless...

**Comment by manishtoons** [comment]
this might help you

all: 108
null: 21
notnull: 108-21 = 87

```
127.0.0.1:6379> FT.SEARCH Project * NOCONTENT LIMIT 0 1
1) (integer) 108
2) "Project:49"
127.0.0.1:6379> FT.SEARCH Project "(@sg_project_code:null)" LIMIT 0 1 NOCONTENT
1) (integer) 21
2) "Project:105"
127.0.0.1:6379> FT.SEARCH Project "-(@sg_project_code:null)" LIMIT 0 1 NOCONTENT
1) (integer) 86
2) "Project:96"
127.0.0.1:6379>


```

**Comment by manishtoons** [comment]
Hey @dvirsky, did you get a chance to see rdb file? Hope im not missing anything!
