### ISSUE TITLE
Dropping an index and recreating causes duplicates if using a database other than 0

### ISSUE THREAD

**Issue by pkmnfrk** [RedisLabsModules/RediSearch#37]
Basically, FT.DROP doesn't seem to clean up all the keys it probably should if you're in a different database. We are running v0.10.

[Here is a script that demonstrates the problem.](https://gist.github.com/pkmnfrk/746d021f075fe6af4bea1f6269303bf5) The first time I run it, I get this output:

```
Recreate index:
OK

Add data:
OK
OK
OK

Index stats:
 1) index_name
 2) test
 3) fields
 4) 1) 1) body
       2) type
       3) TEXT
       4) weight
       5) "1"
 5) num_docs
 6) "3"
 7) max_doc_id
 8) "3"
 9) num_terms
10) "16"
11) num_records
12) "16"
13) inverted_sz_mb
14) "7.62939453125e-05"
15) inverted_cap_mb
16) "0"
17) inverted_cap_ovh
18) "inf"
19) offset_vectors_sz_mb
20) "1.52587890625e-05"
21) skip_index_size_mb
22) "0"
23) score_index_size_mb
24) "0"
25) doc_table_size_mb
26) "9.72747802734375e-05"
27) key_table_size_mb
28) "0.00010013580322265625"
29) records_per_doc_avg
30) "5.333333333333333"
31) bytes_per_record_avg
32) "5"
33) offsets_per_term_avg
34) "1"
35) offset_bits_per_record_avg
36) "8"

Query:
1) (integer) 1
2) "d1"
3) (empty list or set)

Drop index:
OK
```

However, the second time I run it, I get:
```
Query:
1) (integer) 2
2) "d1"
3) (empty list or set)
4) "d1"
5) (empty list or set)
```

A third time yields three results, etc.

If you edit the script to target db 0, then it behaves the way you expect.

**Comment by dvirsky** [comment]
It's a bug in redis itself (https://github.com/antirez/redis/issues/3851), so until further notice, please avoid using a db other than 0. This should be fixed before Redis 4.0. cc: @antirez

**Comment by dvirsky** [comment]
I'm keeping the issue open so we can discuss and verify it once the redis issue is sorted.

**Comment by pkmnfrk** [comment]
Good to know! Thanks!

**Comment by dvirsky** [comment]
While we're on the subject of warnings, please avoid using the module with AOF persistence. I should specify both of these somewhere indeed.

**Comment by pkmnfrk** [comment]
At the risk of exposing my Redis ignorance, you mean specifically AOF; i.e. regular RDP persistence is okay?

**Comment by dvirsky** [comment]
exactly. the default works just fine.

**Comment by pkmnfrk** [comment]
Got it! *scribbles into deployment notes*

**Comment by dvirsky** [comment]
The underlying redis issue has been fixed, this should be fine with latest redis unstable.

**Comment by TvoroG** [comment]
Hi, @dvirsky! I still cannot create index with db != 0. How can I fix this problem? Should I just remove [these lines](https://github.com/RedisLabsModules/RediSearch/blob/9fe887d26b66310a5076b72a08d39eb0202c6969/src/module.c#L931-L933)?

**Comment by dvirsky** [comment]
You just can't. ¯\_(ツ)_/¯
