### ISSUE TITLE
RediSearch - FT.SEARCH with Field Modifiers or INFIELDS option

### ISSUE THREAD

**Issue by nreddipalle** [RedisLabsModules/RediSearch#86]
Trying to perform FT.SEARCH using Field Modifier and INFIELDS option but getting wrong results. Please see below.
![image](https://user-images.githubusercontent.com/28302399/27893754-bd1e2d4a-61d5-11e7-97c5-02362f1b3604.png)
I mentioned to search within Title but got result even if it contains in description.
![image](https://user-images.githubusercontent.com/28302399/27893786-ebaf7218-61d5-11e7-9859-df2f50ad6f3c.png)
Please suggest the right syntax if I am doing wrong.
Thanks in advance.

**Comment by dvirsky** [comment]
It could be a bug in the prefix expansion. let me check something similar. Also can you run FT.EXPLAIN on it and paste the output?

**Comment by dvirsky** [comment]
Also, please send me a dump of FT.INFO on your index

**Comment by dvirsky** [comment]
Ok, it was indeed a byproduct of the prefix expansion. It's currently fixed in master. Please pull again and try. no need to reindex. Thanks for catching this!

**Comment by nreddipalle** [comment]
I did a pull again, built my docker image but still getting the same results. 
![image](https://user-images.githubusercontent.com/28302399/27912889-5768fadc-622c-11e7-93d1-28db8cbf0a76.png)
Docker:0>ft.info Ticket
 1)  "index_name"
 2)  "Ticket"
 3)  "fields"
 4)    1)      1)    "TicketID"
   2)    "type"
   3)    "NUMERIC"
   4)    "SORTABLE"

  2)      1)    "Title"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "4"

  3)      1)    "Description"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "3"

  4)      1)    "ProjectID"
   2)    "type"
   3)    "NUMERIC"

  5)      1)    "Tag"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "1"

  6)      1)    "Comment"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "1"


 5)  "num_docs"
 6)  "101988"
 7)  "max_doc_id"
 8)  "101988"
 9)  "num_terms"
 10)  "182963"
 11)  "num_records"
 12)  "8525329"
 13)  "inverted_sz_mb"
 14)  "70.94488525390625"
 15)  "inverted_cap_mb"
 16)  "0"
 17)  "inverted_cap_ovh"
 18)  "0"
 19)  "offset_vectors_sz_mb"
 20)  "29.066169738769531"
 21)  "skip_index_size_mb"
 22)  "0"
 23)  "score_index_size_mb"
 24)  "0"
 25)  "doc_table_size_mb"
 26)  "4.4741134643554688"
 27)  "key_table_size_mb"
 28)  "2.4865322113037109"
 29)  "records_per_doc_avg"
 30)  "83.591491155822254"
 31)  "bytes_per_record_avg"
 32)  "8.7258924552941011"
 33)  "offsets_per_term_avg"
 34)  "2.9477098185888191"
 35)  "offset_bits_per_record_avg"
 36)  "9.7024593043365037"
Results below with the new build:
![image](https://user-images.githubusercontent.com/28302399/27913009-ba37d746-622c-11e7-800d-c5b0c20f0559.png)
![image](https://user-images.githubusercontent.com/28302399/27913031-c606aa48-622c-11e7-834d-6f592834f15e.png)

I did try with INFIELDS option and got the same result:
![image](https://user-images.githubusercontent.com/28302399/27913132-1cbcdfba-622d-11e7-8e68-93050a348d7b.png)

**Comment by nreddipalle** [comment]
I did a pull again, built my docker image and the results are similar as
before.

RUN cd /usr/local/src && \
git clone https://github.com/RedisLabsModules/RediSearch.git RediSearch && \
cd RediSearch && \
make && \
cp src/module.so /usr/local/lib/redisearch.so && \
cd /usr/local/src && \
rm -rf /usr/local/src/RediSearch

**Comment by dvirsky** [comment]
Can you send me your RDB please? Also, the latest master changed the name of the module file from `module.so` to `redisearch.so`, so you'll need to change your docker recipe if you haven't.

**Comment by nreddipalle** [comment]
ok thanks. i need to change my docker recipe:
RUN cd /usr/local/src && \
	git clone https://github.com/RedisLabsModules/RediSearch.git RediSearch && \
	cd RediSearch && \
	make && \
	cp src/**module**.so /usr/local/lib/redisearch.so && \
	cd /usr/local/src && \
	rm -rf /usr/local/src/RediSearch

changing from cp src/module.so to cp src/redisearch.so... i will do a retest and share the RDB if it fails..

**Comment by dvirsky** [comment]
Cool. If it works just close the issue. There was indeed a bug I a managed to reproduce and fix, but perhaps there was more than one :)

**Comment by nreddipalle** [comment]
the redis server is aborting now after load of redis.config file which includes this:
################################## MODULES 

# Load modules at startup. If the server is not able to load modules
# it will abort. It is possible to use multiple loadmodule directives.
#
**loadmodule /usr/local/lib/redisearch.so**
#####################################
This is my complete docker file recipe:
RUN cd /usr/local/src && \
	git clone https://github.com/RedisLabsModules/RediSearch.git RediSearch && \
	cd RediSearch && \
	make && \
	cp src/redisearch.so /usr/local/lib/redisearch.so && \
	cd /usr/local/src && \
	rm -rf /usr/local/src/RediSearch
	
ADD redis.conf /etc/redis.conf

**Comment by nreddipalle** [comment]
For some reason redis server is getting aborted on loading the redisearch module.
this is my complete recipe and config file entry
RUN cd /usr/local/src && \
	git clone https://github.com/RedisLabsModules/RediSearch.git RediSearch && \
	cd RediSearch && \
	make && \
	cp src/redisearch.so /usr/local/lib/redisearch.so && \
	cd /usr/local/src && \
	rm -rf /usr/local/src/RediSearch
	
ADD redis.conf /etc/redis.conf

# Load modules at startup. If the server is not able to load modules
# it will abort. It is possible to use multiple loadmodule directives.
#
loadmodule /usr/local/lib/redisearch.so

FYI - for testing, I removed this module and the server is loading fine. any ideas??

**Comment by dvirsky** [comment]
I can't help you without the output of the redis startup.

**Comment by nreddipalle** [comment]
Found the issue. Looks like a redis compatability issue. 
Log said:
 <ft> ***** FATAL: Incompatible version of redis 4.0 detected. *****
                                Redis 4.0 RC3 or earlier will not run this module properly
                                Please use the latest 4.0 branch instead from https://github.com/antirez/redis/archive/4.0.zip
                                Redis will exit now!
11811:M 06 Jul 16:46:40.717 # Module /usr/local/lib/redisearch.so initialization failed. Module not loaded

I am currently using 
git clone https://github.com/antirez/redis.git redis -b 4.0-rc3.

**Comment by dvirsky** [comment]
Then use redis unstable please

**Comment by dvirsky** [comment]
Glad to hear and thanks for catching that!

BTW Mind sharing the current fixed docker file? I want to create a ready to use docker image for redisearch.

**Comment by nreddipalle** [comment]
FROM ubuntu:latest

RUN apt-get update && apt-get -y install build-essential git && apt-get clean

RUN mkdir /var/lib/redis

RUN cd /usr/local/src && \
	git clone https://github.com/antirez/redis.git redis && \
	cd /usr/local/src/redis && \
	make && \
	make install && \
	cd /usr/local/src && rm -rf /usr/local/src/redis

RUN cd /usr/local/src && \
	git clone https://github.com/RedisLabsModules/RediSearch.git RediSearch && \
	cd RediSearch && \
	make && \
	cp src/redisearch.so /usr/local/lib/redisearch.so && \
	cd /usr/local/src && \
	rm -rf /usr/local/src/RediSearch
	
ADD redis.conf /etc/redis.conf

## NOTE: These cannot be set in docker! Redis is just going to have to live with them
##
#RUN sysctl vm.overcommit_memory=1 && echo never > /sys/kernel/mm/transparent_hugepage/enabled

CMD ["redis-server", "/etc/redis.conf"]

**Comment by dvirsky** [comment]
Thanks!

**Comment by nreddipalle** [comment]
To my understanding, the below two commands should fetch same results. one contains " " between the args. As I send a single request from my application, i expect 5 results but it is displaying 0. the workaround for now is to send multiple requests (one for Title and one for description) rather than a single call.
![image](https://user-images.githubusercontent.com/28302399/27974572-932e913e-632c-11e7-89f1-f62fc982d80c.png)

Also, INKEYS option is crashing the redis when the values sent are around 8000. it used to work fine for previous versions even when i send a million keys.

**Comment by dvirsky** [comment]
Re 1 - the first example is the correct way, in the second one the second part of the query is viewed as a different argument, and is ignored. I don't think it is related to this bug, so can I please ask you to send me: 1. the dump of FT.EXPLAIN for that query, and if possible - the RDB of your database so I can load it and see what's going on. If it's something other than ambiguous syntax on the parser side, let's open another issue.

Try making the query less ambiguous: `(@Title:(redis|redis*)) (@Description:redis)`. Are you sure BTW that there are five results where redis is both in the title and the description? 

Re the crash - will look into it, the RDB will help, along with an example query. If it's not possible to send those, then at least copy the output of the crash report. 

Thanks!

**Comment by dvirsky** [comment]
Is there any chance that the query you meant was `(@Title:redis|redis*) ~(@Description:redis)`, meaning they can optionally have redis in the description as well? I mean, if the first part of the query brings up 5 documents, to get 5 results in the pattern of your query - you need all of them to contain redis in the description as well to get 5 results from both parts of the query.

**Comment by nreddipalle** [comment]
My requirement within that particular query was to do an exact search and
substring search within Title and only an exact search for description.

**Comment by dvirsky** [comment]
Your query example requires that both fields match. Your description sounds like you need either rules to match. If so, use the or operator. Are you sure that all five results have redis both in title AND description?

**Comment by nreddipalle** [comment]
My requirement is to search for Redis and Redis* under Title and only Redis under Description. when passing both the arguments in the same call, it is returning empty string as shown above. The five results displayed in my above image is pertaining to Title (Redis |Redis* within Title). I expect the same to showup when passing Description too with an OR but it is returning an empty string.
![image](https://user-images.githubusercontent.com/28302399/28021860-4ecc5d50-6557-11e7-8e57-37d08c869f23.png)

**Comment by dvirsky** [comment]
The operator for or is `|` not `OR`. your query should be:
`(@Title:redis|redis*) | (@Desciption:redis)`.

**Comment by nreddipalle** [comment]
Thanks. I will continue looking into it and let know if any more issues comes up. One  question, Is there any way I can pass a list of TicketIDs to search only in those ticketIDs ( documentIds in these case like scoped items). I already have the ticketIDs stored as a list in REDIS and would like the search occur only within those ticketIDs. I tried INKEYS option but my TicketIDs count is generally larger than 50000 regularly.

**Comment by dvirsky** [comment]
First of all - I didn't manage to crash redis with huge INKEYS lists. I tried half a million and it still worked and rather fast even.

The simplest option would be to use a special field containing the group or groups of tickets you want to limit yourself to, such as a category, status, etc then add something like "@category:my_category" or "@status:resolved" to the query. This will be very fast and unlimited in size, and you can use multiple tags/categories whatever it is you want. It is also possible to update the tickets if something changes.

**Comment by nreddipalle** [comment]
Thanks for the suggestion. Is there any limit in passing the number of search values. If I am saving TicketID too, Is it ok if I send a huge list of TicketIds to SEARCH parameter @TicketID:12345|123345|167435| and so on...

**Comment by dvirsky** [comment]
no, that will not work. what I mean is that if you have a list of ticket ids you want to filter by, that is a group of ids, right? why not just declare what they are as a property? What are those id lists semantically?

**Comment by nreddipalle** [comment]
The id lists I am referring to are User Access Tickets. I am storing them in REDIS as sets per userID as the key and ticketIds as members. so now as part of search I need to make sure the result is only scoped towards that list. The search should not return results which user is not scoped to see.

**Comment by nreddipalle** [comment]
I will see whether that is possible. If RediSearch could allow passing a SET as part of INKEYS option that would be great. Is it a possible enhancement in the future??

**Comment by nreddipalle** [comment]
any wrong with this syntax??
![image](https://user-images.githubusercontent.com/28302399/28041276-cde7e700-6596-11e7-902e-0e266e97c8c8.png)

**Comment by dvirsky** [comment]
Regarding intersecting with sets - it's possible but will not perform much better than INKEYS, besides saving the network overhead. Let me think about it. 

Regarding the ticketId - unless you've created `TicketId` as a numeric field in your schema and are passing that as a field and not just the id - we do not index the keys themselves.

**Comment by nreddipalle** [comment]
I do have the TicketID as a numeric field. please see below.
1)  "index_name"
 2)  "Ticket"
 3)  "fields"
 4)    1)      1)    "TicketID"
   2)    "type"
   3)    "NUMERIC"
   4)    "SORTABLE"

  2)      1)    "Title"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "4"

  3)      1)    "Description"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "3"

  4)      1)    "ProjectID"
   2)    "type"
   3)    "NUMERIC"

  5)      1)    "Tag"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "1"

  6)      1)    "Comment"
   2)    "type"
   3)    "TEXT"
   4)    "weight"
   5)    "1"

**Comment by dvirsky** [comment]
Filtering numeric fields is done with `@Field:[{min} {max}]`. If you don't want ranges you can use a text field.

**Comment by nreddipalle** [comment]
ok. got it thanks. to use INKEYS option, I assume I need to savedocuments so that it create keys for each ticket. Am i correct??

**Comment by dvirsky** [comment]
No, INKEYS refers to the document id you specified when inserting the data with FT.ADD, it applies even if NOSAVE is specified (If this is what you are asking);

**Comment by nreddipalle** [comment]
Thanks. for now I will try with INKEYS option and see how it performs. The max amount of values I could pass to INKEYS option is around 101721. Hope it wont crash...

**Comment by nreddipalle** [comment]
INKEYS worked fine when performing the SEARCH in normal search but it is crashing when prefix search is included. @Title:redis worked fine but @Title:redis|redis* is failing. 
![image](https://user-images.githubusercontent.com/28302399/28046975-641b7214-65b5-11e7-8b56-c00820f26aa7.png)

**Comment by dvirsky** [comment]
I'm not sure what's going on here, but I've fixed a similar issue with prefixes yesterday, could you please use version 0.19.1 and try? Also, I'm closing this issue, if there is a crash it's an unrelated issue and you should open a new one.

**Comment by nreddipalle** [comment]
the above issue is resolved with 0.19.1. On testing with INKEYS option my results vary.
please see below.
![image](https://user-images.githubusercontent.com/28302399/28076414-aeb02ffa-662c-11e7-9e9a-8a2b0308079a.png)

**Comment by nreddipalle** [comment]
Docker:0>ft.search Ticket (@Title:redis|redis*) NOCONTENT
 1)  "5"
 2)  "179094"
 3)  "125158"
 4)  "141536"
 5)  "109642"
 6)  "108398"

WHEN passing the same values within INKEYS, the result is 0 always. 
Please see below for the complete query: ( I checked atleast 4 of the them exist in the INKEYS values)

[redis query.txt](https://github.com/RedisLabsModules/RediSearch/files/1139468/redis.query.txt)

![image](https://user-images.githubusercontent.com/28302399/28077275-502d041e-662f-11e7-8928-2529278e4196.png)
![image](https://user-images.githubusercontent.com/28302399/28077290-5e9faa74-662f-11e7-8c88-36f4ac42f76a.png)
